version: '3'

services:
  payment_service:
    container_name: payment_service
    build:
      context: .
    image: payment_service_app
    ports:
      - "8080:8080"
    environment:
        SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/payments
    depends_on:
      - db

  db:
    container_name: postgres_db
    image: postgres:13.3
    environment:
      - POSTGRES_PASSWORD=1
      - POSTGRES_USER=postgres
      - POSTGRES_DB=payments
    ports:
      - "5434:5432"
